autocmd BufNewFile,BufRead *.json set ft=javascript

au FileType xml exe ":silent 1,$!xmllint --format --recover - 2>/dev/null"
map <leader>jt  <Esc>:%!json_xs -f json -t json-pretty<CR>

syntax on
colorscheme inkpot 
set hlsearch
set ruler
